services:
  - type: web
    name: multi-platform-video-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 300 app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
